### ISSUE TITLE
an appendix of functions

### ISSUE THREAD

**Issue by philmcaleer** [PsyTeachR/template#1]
Would be good if we could create an appendix that lists the functions that appear in a book and where they appeared - potentially even with a brief definition of the function.  When we spoke Lisa, you suggested this might be possible using the autolink aspect of the bs4 render to search the html files and their link to the rdrr.io pages and pull that info into a table such as:

|function|definition|chapter|
|:--------:|:---------:|:--------:|
|rnorm() | blah blah| 1, 3, 4  |

In a similar fashion to how `glossary()` and `glossary_table()` work in the glossary package.

**Comment by debruine** [comment]
I'll think about this for the quarto booktem
