### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by facusoto** [PsyTeachR/template#2]
Hello, I tried to use the template but always the same error occurs, the generator is not found.

![image](https://user-images.githubusercontent.com/81945511/233093657-419c8e4a-c482-4eb3-a9b9-210deb55fcf6.png)

By changing the template structure and locating the files in the "book" folder in the root index I could make it render but never with the proposed structure. Does anyone know what this is due to and how I can fix it?

**Comment by debruine** [comment]
Try the following code (in the _render.R file, which I know should be a makefile, sorry)

`xfun::in_dir("book", bookdown::render_book("index.Rmd", "bookdown::bs4_book"))`
